name: flutter_hive_dersleri
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.7





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
